use_frameworks!

target 'DLMAlertController_Example' do
  pod 'DLMAlertController', :path => '../'
  pod 'DLMFoundation', :path => '../../DLMFoundation/'
  pod 'DLMKit', :path => '../../DLMKit/'

  target 'DLMAlertController_Tests' do
    inherit! :search_paths

    
  end
end
